### ISSUE TITLE
combine multiple RUN lines into a single line

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/generator#2]
this will minimize the number of layers in the docker image

**Comment by Michael-D-Johnson** [comment]
I install pyclowder as a dependency (assuming the user doesn't and shouldn't worry about it). If they do specify it, it will install again overriding the default install. To simplify the logic, I have not tried to remove this extra RUN line.

So if someone has a requirements.txt file the Dockerfile would look like this:

RUN pip install pyclowder==2.4.0
RUN pip install -r requirements.txt

If they instead only have dependencies specified in the "build" section of the extractor_info.json file it would look like this:
RUN pip install pyclowder==2.4.0
RUN pip install jinja pandas==1.2.1

So it would reduce the number of lines by n-1 dependencies specified. Is this satisfactory or would the preference be to try an d remove the default pyclowder RUN line?

**Comment by robkooper** [comment]
you can use:

```
RUN pip install pyclowder==2.4.0 && \
    pip install -r requirements.txt
```

**Comment by Michael-D-Johnson** [comment]
Of course! Will update that.

**Comment by Michael-D-Johnson** [comment]
Okay this is done.
